version: '3.4'

services:
  sheipados-nutrition-react:
    container_name: sheipados-nutrition-react
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './:/app'
    network_mode: "host"