export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';